version: '3'

services:
  recursor:
    container_name: recursor
    image: testing/powerdns-auth-docker:armhf-latest
    build:
      context: ./powerdns-recursor-docker/
      dockerfile: Dockerfile.armhf
      args:
        PDNS_VERSION: 42
    restart: always
    ports:
      - 54:53/tcp
      - 54:53/udp
    environment:
      PDNS_AUTH_API_HOST: 10.10.0.4
      PDNS_AUTH_API_PORT: 8001
      PDNS_AUTH_API_KEY: KGJp7W2RADcw73wm
      EXTRA_FORWARD: "os.larnet.eu.=10.10.0.8"
