FROM debian:buster

LABEL maintainer="emil@jacero.se"

ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
# Build arguments with sane defaults
ARG PDNS_VERSION=44

RUN apt update && apt -y install tzdata
RUN apt install -y ca-certificates curl wget gnupg2 jq dnsutils python3 python3-pip python3-psycopg2 && apt -y upgrade

# NOTE: DO NOT OVERWRITE THIS VARIABLE... EVER!
ENV POWERDNS_VERSION=$PDNS_VERSION

RUN touch /etc/apt/sources.list.d/pdns.list && echo deb [arch=armhf] http://repo.powerdns.com/raspbian buster-rec-$PDNS_VERSION main >> /etc/apt/sources.list.d/pdns.list
RUN echo "Package: pdns-*" >> /etc/apt/preferences.d/pdns && \
    echo "Pin: origin repo.powerdns.com" >> /etc/apt/preferences.d/pdns && \
    echo "Pin-Priority: 600" >> /etc/apt/preferences.d/pdns
RUN curl -fsSL https://repo.powerdns.com/FD380FBB-pub.asc | apt-key add - && apt update
RUN apt -y install pdns-recursor

# Download latest named.root as fallback if entrypoint fails to download
RUN wget https://www.internic.net/domain/named.root -O /var/named.root

# Set timezone
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Installing python modules
ADD requirements.txt /
RUN pip3 install -r requirements.txt

# Prepare directories for PowerDNS
RUN mkdir -p /var/run/powerdns-recursor && chown -R 101:101 /var/run/powerdns-recursor
RUN mkdir -p /var/run/pdns-recursor && chown -R 101:101 /var/run/pdns-recursor

# Add src
ADD src /app

WORKDIR /app
EXPOSE 53/tcp 53/udp
STOPSIGNAL SIGTERM
ENTRYPOINT /app/entrypoint.py
